name: Run Tests with Docker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t python-katas .

      - name: Run tests inside container
        run: docker run python-katas