name: Run Tests and Deploy

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build test image
              run: docker build -f dockerfile.test -t python-katas-test .

            - name: Run tests inside container
              run: docker run python-katas-test

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Render
              run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
